snowtricks_o_auth:
    resource: "@SnowtricksOAuthBundle/Resources/config/routing.yml"
    prefix:   /

snowtricks_core:
    resource: "@SnowtricksCoreBundle/Resources/config/routing.yml"
    prefix:   /

elfinder:
  resource: "@FMElfinderBundle/Resources/config/routing.yml"

login:
  path: /login
  defaults:
    _controller: SnowtricksUserBundle:Security:login

login_check:
  path: /login_check

logout:
  path: /logout
